install.packages("tidyverse")
install.packages("packcircles")
install.packages("viridis")
install.packages('Rcpp')
install.packages("readxl")
install.packages("zoo")
install.packages("tinytex")
install.packages("xfun")
install.packages("htmltools")
install.packages("digest")
install.packages("magrirtr")
install.packages("stringi")
# install.packages("LaTeX")
install.packages("yaml")
